In [1]:
import numpy as np

num_features = 1
loc = 1

x_train = np.vstack([np.random.normal(size=(9000, num_features)), np.random.normal(loc=loc, size=(1000, num_features))])
x_train.shape

(10000, 1)

In [2]:
y_train = np.hstack([np.zeros((9000,)), np.ones((1000,))])
y_train.shape

(10000,)

In [3]:
x_test = np.vstack([np.random.normal(size=(900, num_features)), np.random.normal(loc=loc, size=(100, num_features))])
x_test.shape

(1000, 1)

In [4]:
y_test = np.hstack([np.zeros((900,)), np.ones((100,))])
y_test.shape

(1000,)

In [5]:
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf
import keras.backend as K

def auc(y_true, y_pred):
    y_true_1 = tf.equal(y_true, 1)
    y_true_0 = tf.equal(y_true, 0)
    a = tf.boolean_mask(y_pred, y_true_1)
    b = tf.boolean_mask(y_pred, y_true_0)
    return K.mean(a[None, :] > b[:, None])

Using TensorFlow backend.


In [6]:
model = Sequential()
#model.add(Dense(100, input_shape=(num_features,), activation='relu'))
#model.add(Dense(100, activation='relu'))
#model.add(Dense(100, activation='relu'))
model.add(Dense(1, input_shape=(num_features,), activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy', auc])

In [7]:
model.fit(x_train, y_train, batch_size=100, epochs=10, validation_data=(x_test, y_test))

Train on 10000 samples, validate on 1000 samples
Epoch 1/10
10000/10000 [==============================] - 1s - loss: 1.0157 - acc: 0.4778 - auc: 0.2452 - val_loss: 0.9492 - val_acc: 0.5070 - val_auc: nan
Epoch 2/10
10000/10000 [==============================] - 0s - loss: 0.9485 - acc: 0.5024 - auc: 0.2471 - val_loss: 0.8863 - val_acc: 0.5340 - val_auc: nan
Epoch 3/10
10000/10000 [==============================] - 0s - loss: 0.8853 - acc: 0.5282 - auc: 0.2445 - val_loss: 0.8278 - val_acc: 0.5540 - val_auc: nan
Epoch 4/10
10000/10000 [==============================] - 0s - loss: 0.8262 - acc: 0.5571 - auc: 0.2416 - val_loss: 0.7733 - val_acc: 0.5830 - val_auc: nan
Epoch 5/10
10000/10000 [==============================] - 0s - loss: 0.7711 - acc: 0.5877 - auc: 0.2467 - val_loss: 0.7225 - val_acc: 0.6140 - val_auc: nan
Epoch 6/10
10000/10000 [==============================] - 0s - loss: 0.7203 - acc: 0.6229 - auc: 0.2442 - val_loss: 0.6761 - val_acc: 0.6500 - val_auc: nan
Epoch 7/10
1000

In [8]:
from sklearn.metrics import confusion_matrix

y_pred = model.predict(x_test)
confusion_matrix(y_pred > 0.5, y_test)

array([[806,  99],
       [ 94,   1]])

In [9]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, y_pred)

0.27083333333333337

In [10]:
model = Sequential()
#model.add(Dense(100, input_shape=(num_features,), activation='relu'))
#model.add(Dense(100, activation='relu'))
#model.add(Dense(100, activation='relu'))
model.add(Dense(1, input_shape=(num_features,), activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy', auc])

In [11]:
from sklearn.utils.class_weight import compute_class_weight

class_weight = compute_class_weight(class_weight='balanced', classes=np.unique(y_train), y=y_train)
class_weight

array([ 0.55555556,  5.        ])

In [12]:
model.fit(x_train, y_train, batch_size=100, epochs=10, validation_data=(x_test, y_test), class_weight=class_weight)

Train on 10000 samples, validate on 1000 samples
Epoch 1/10
10000/10000 [==============================] - 0s - loss: 0.6780 - acc: 0.5749 - auc: 0.7575 - val_loss: 0.6615 - val_acc: 0.5950 - val_auc: nan
Epoch 2/10
10000/10000 [==============================] - 0s - loss: 0.6363 - acc: 0.6595 - auc: 0.7507 - val_loss: 0.6221 - val_acc: 0.6870 - val_auc: nan
Epoch 3/10
10000/10000 [==============================] - 0s - loss: 0.6001 - acc: 0.7516 - auc: 0.7607 - val_loss: 0.5877 - val_acc: 0.7910 - val_auc: nan
Epoch 4/10
10000/10000 [==============================] - 0s - loss: 0.5685 - acc: 0.8336 - auc: 0.7595 - val_loss: 0.5576 - val_acc: 0.8590 - val_auc: nan
Epoch 5/10
10000/10000 [==============================] - 0s - loss: 0.5404 - acc: 0.8816 - auc: 0.7545 - val_loss: 0.5309 - val_acc: 0.8870 - val_auc: nan
Epoch 6/10
10000/10000 [==============================] - 0s - loss: 0.5153 - acc: 0.8983 - auc: 0.7534 - val_loss: 0.5070 - val_acc: 0.8930 - val_auc: nan
Epoch 7/10
1000

In [13]:
y_pred = model.predict(x_test)
confusion_matrix(y_pred > 0.5, y_test)

array([[900,  98],
       [  0,   2]])

In [14]:
roc_auc_score(y_test, y_pred)

0.72916666666666674

In [15]:
model = Sequential()
#model.add(Dense(100, input_shape=(num_features,), activation='relu'))
#model.add(Dense(100, activation='relu'))
#model.add(Dense(100, activation='relu'))
model.add(Dense(1, input_shape=(num_features,), activation='sigmoid'))

from utils import sample_binomial
from keras.losses import binary_crossentropy

def reinforce_loss(y_true, y_pred):
    y_samp = sample_binomial(y_pred)
    rewards = auc(y_true, y_samp)
    baseline = auc(y_true, y_pred)
    advantages = rewards - baseline
    return advantages * binary_crossentropy(y_samp, y_pred)

model.compile(loss=reinforce_loss, optimizer='adam', metrics=['accuracy', auc])

In [16]:
model.fit(x_train, y_train, batch_size=100, epochs=10, validation_data=(x_test, y_test))

Train on 10000 samples, validate on 1000 samples
Epoch 1/10
10000/10000 [==============================] - 0s - loss: -0.0570 - acc: 0.4652 - auc: 0.2452 - val_loss: nan - val_acc: 0.4920 - val_auc: nan
Epoch 2/10
10000/10000 [==============================] - 0s - loss: -0.0593 - acc: 0.4644 - auc: 0.2471 - val_loss: nan - val_acc: 0.4890 - val_auc: nan
Epoch 3/10
10000/10000 [==============================] - 0s - loss: -0.0612 - acc: 0.4643 - auc: 0.2443 - val_loss: nan - val_acc: 0.4920 - val_auc: nan
Epoch 4/10
10000/10000 [==============================] - 0s - loss: -0.0565 - acc: 0.4671 - auc: 0.2401 - val_loss: nan - val_acc: 0.4920 - val_auc: nan
Epoch 5/10
10000/10000 [==============================] - 0s - loss: -0.0603 - acc: 0.4671 - auc: 0.2470 - val_loss: nan - val_acc: 0.4920 - val_auc: nan
Epoch 6/10
10000/10000 [==============================] - 0s - loss: -0.0546 - acc: 0.4679 - auc: 0.2420 - val_loss: nan - val_acc: 0.4920 - val_auc: nan
Epoch 7/10
10000/10000 [===

In [17]:
y_pred = model.predict(x_test)
confusion_matrix(y_pred > 0.6, y_test)

array([[580,  92],
       [320,   8]])

In [18]:
roc_auc_score(y_test, y_pred)

0.27083333333333337

In [23]:
model = Sequential()
#model.add(Dense(100, input_shape=(num_features,), activation='relu'))
#model.add(Dense(100, activation='relu'))
#model.add(Dense(100, activation='relu'))
model.add(Dense(1, input_shape=(num_features,), activation='sigmoid'))

def auc_loss(y_true, y_pred):
    y_true_1 = tf.equal(y_true[:, 0], 1)
    y_true_0 = tf.equal(y_true[:, 0], 0)
    prob_1 = tf.boolean_mask(y_pred, y_true_1)
    prob_0 = tf.boolean_mask(y_pred, y_true_0)
    agtb = tf.cast(prob_1[:, None] > prob_0[None, :], tf.float32)
    baseline = tf.reduce_mean(agtb)
    rewards_1 = tf.reduce_mean(agtb, axis=1)
    rewards_0 = tf.reduce_mean(agtb, axis=0)
    advantages_1 = rewards_1 - baseline
    advantages_0 = rewards_0 - baseline
    return tf.reduce_mean(advantages_1 * -tf.log(prob_1)) + tf.reduce_mean(advantages_0 * -tf.log(prob_0))

model.compile(loss=auc_loss, optimizer='adam', metrics=['accuracy', auc])

In [24]:
model.fit(x_train, y_train, batch_size=10000, epochs=10, validation_data=(x_test, y_test))

Train on 10000 samples, validate on 1000 samples
Epoch 1/10
10000/10000 [==============================] - 0s - loss: 0.0013 - acc: 0.5335 - auc: 0.7562 - val_loss: 0.0048 - val_acc: 0.5080 - val_auc: 0.7292
Epoch 2/10
10000/10000 [==============================] - 0s - loss: 0.0013 - acc: 0.5338 - auc: 0.7562 - val_loss: 0.0048 - val_acc: 0.5080 - val_auc: 0.7292
Epoch 3/10
10000/10000 [==============================] - 0s - loss: 0.0013 - acc: 0.5342 - auc: 0.7562 - val_loss: 0.0047 - val_acc: 0.5080 - val_auc: 0.7292
Epoch 4/10
10000/10000 [==============================] - 0s - loss: 0.0012 - acc: 0.5347 - auc: 0.7562 - val_loss: 0.0047 - val_acc: 0.5080 - val_auc: 0.7292
Epoch 5/10
10000/10000 [==============================] - 0s - loss: 0.0012 - acc: 0.5352 - auc: 0.7562 - val_loss: 0.0047 - val_acc: 0.5090 - val_auc: 0.7292
Epoch 6/10
10000/10000 [==============================] - 0s - loss: 0.0012 - acc: 0.5355 - auc: 0.7562 - val_loss: 0.0047 - val_acc: 0.5110 - val_auc: 0.72

In [25]:
y_pred = model.predict(x_test)
confusion_matrix(y_pred > 0.5, y_test)

array([[437,  24],
       [463,  76]])

In [26]:
roc_auc_score(y_test, y_pred)

0.72916666666666674